### ISSUE TITLE
Add research section

### ISSUE THREAD

**Issue by ch3njust1n** [bumic/website#4]
Section should include

1. Title of work
2. BUMIC member's name
3. Year
4. Abstract
5. Any links to open source if available

**Comment by ch3njust1n** [comment]
Can you also add a research link to the nav bar and change the section title from "RESEARCHES" to just "RESEARCH"

**Comment by zuik** [comment]
Commit 1d050b668dacd8bca26ab749303fb0e0e4df44a1
